from webapps.auth import route_login
from webapps.auth import route_logout
from webapps.routes import route_about
from webapps.routes import route_home
from webapps.routes import route_kontakt
from webapps.routes import route_registrace
from webapps.routes import route_ucet
from webapps.routes import route_zalozit_pojisteni
from webapps.routes import route_zalozit_udalost
