
# Project information
site_name: Pojisteni App
site_url: https://3p1463k.github.io/pojisteni/
site_author: Evzen Ptacek


# Repository
repo_name: 3p1463k/pojisteni
repo_url: https://github.com/3p1463k/pojisteni

# Navigation

nav:
    - 'index.md'
    - 'layout.md'
    - 'instalation.md'
    - 'core.md'
    - 'databaze.md'
    - 'apis.md'
    - 'admin.md'
    - 'schemas.md'
    - 'models.md'
    - 'templates.md'
    - 'webapps.md'
    - 'tests.md'
    - 'codeclean.md'
    - 'deploy.md'
    - 'documentation.md'




# Configuration
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Ztmavit
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: red
    toggle:
      icon: material/weather-night
      name: Svetlo

  features:
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.expand




# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



# Extensions
plugins:
  - glightbox
  - search
